[2022-05-11 18:28:47,505] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.staging scheduled__2022-04-02T00:00:00+00:00 [queued]>
[2022-05-11 18:28:47,514] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.staging scheduled__2022-04-02T00:00:00+00:00 [queued]>
[2022-05-11 18:28:47,514] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 18:28:47,514] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-11 18:28:47,514] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-11 18:28:47,524] {taskinstance.py:1264} INFO - Executing <Task(riotOperator): staging> on 2022-04-02 00:00:00+00:00
[2022-05-11 18:28:47,529] {standard_task_runner.py:52} INFO - Started process 4093 to run task
[2022-05-11 18:28:47,531] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'staging', 'scheduled__2022-04-02T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp14472luc', '--error-file', '/tmp/tmp1qmvgbfo']
[2022-05-11 18:28:47,532] {standard_task_runner.py:77} INFO - Job 65: Subtask staging
[2022-05-11 18:28:47,572] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.staging scheduled__2022-04-02T00:00:00+00:00 [running]> on host c411fdaf6506
[2022-05-11 18:28:47,613] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=staging
AIRFLOW_CTX_EXECUTION_DATE=2022-04-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-02T00:00:00+00:00
[2022-05-11 18:28:47,613] {riot_operator.py:61} INFO - StageToAzureLake not implemented yet
[2022-05-11 18:28:47,621] {riot_operator.py:68} INFO - <bound method WasbHook.get_conn of <airflow.providers.microsoft.azure.hooks.wasb.WasbHook object at 0x7f119a984f70>>
[2022-05-11 18:28:47,621] {riot_operator.py:69} INFO - Created Azure Connection
[2022-05-11 18:28:47,627] {riot_operator.py:72} INFO - Created Riot Connection
[2022-05-11 18:28:47,852] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-05-11 18:28:47,852] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-05-11 18:28:47,852] {Limits.py:87} INFO - rate limit changed from 0/0s to 2000/60s
[2022-05-11 18:28:48,140] {Limits.py:87} INFO - rate limit changed from 0/0s to 20/1s
[2022-05-11 18:28:48,141] {Limits.py:87} INFO - rate limit changed from 0/0s to 100/120s
[2022-05-11 18:28:48,141] {Limits.py:87} INFO - rate limit changed from 0/0s to 500/10s
[2022-05-11 18:28:48,142] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 62, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 86, in upload_to_azureLake
    match_details = match['info']['participants']
TypeError: string indices must be integers
[2022-05-11 18:28:48,153] {taskinstance.py:1272} INFO - Marking task as UP_FOR_RETRY. dag_id=league_of_legends_dag, task_id=staging, execution_date=20220402T000000, start_date=20220511T182847, end_date=20220511T182848
[2022-05-11 18:28:48,165] {standard_task_runner.py:89} ERROR - Failed to execute job 65 for task staging
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 62, in execute
    self.upload_to_azureLake()
  File "/opt/airflow/plugins/custom_operators/riot_operator.py", line 86, in upload_to_azureLake
    match_details = match['info']['participants']
TypeError: string indices must be integers
[2022-05-11 18:28:48,186] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-11 18:28:48,212] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
