[2022-06-20 06:47:39,290] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchdetails.azure_matchdetails_snowflake scheduled__2022-06-18T00:00:00+00:00 [None]>
[2022-06-20 06:47:39,299] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchdetails.azure_matchdetails_snowflake scheduled__2022-06-18T00:00:00+00:00 [None]>
[2022-06-20 06:47:39,300] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:47:39,300] {taskinstance.py:1244} INFO - Starting attempt 3 of 4
[2022-06-20 06:47:39,300] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 06:47:39,311] {taskinstance.py:1264} INFO - Executing <Task(AzureDataLakeToSnowflakeTransferOperator): paths.path_matchdetails.azure_matchdetails_snowflake> on 2022-06-18 00:00:00+00:00
[2022-06-20 06:47:39,316] {standard_task_runner.py:52} INFO - Started process 236 to run task
[2022-06-20 06:47:39,319] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'paths.path_matchdetails.azure_matchdetails_snowflake', 'scheduled__2022-06-18T00:00:00+00:00', '--job-id', '184', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmp7f4ydqss', '--error-file', '/tmp/tmpdnknqynk']
[2022-06-20 06:47:39,320] {standard_task_runner.py:77} INFO - Job 184: Subtask paths.path_matchdetails.azure_matchdetails_snowflake
[2022-06-20 06:47:39,362] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.paths.path_matchdetails.azure_matchdetails_snowflake scheduled__2022-06-18T00:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-20 06:47:39,404] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=paths.path_matchdetails.azure_matchdetails_snowflake
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-18T00:00:00+00:00
[2022-06-20 06:47:39,404] {azureToSnowflake.py:73} INFO - Executing COPY command...
[2022-06-20 06:47:39,413] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.12, Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2022-06-20 06:47:39,413] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-06-20 06:47:39,413] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-06-20 06:47:40,010] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-06-20 06:47:40,156] {cursor.py:734} INFO - query execution done
[2022-06-20 06:47:40,157] {snowflake.py:324} INFO - Running statement: COPY INTO STAGING_MATCHDETAILS
FROM @MY_AZURE_MATCH_DETAILS_STAGE/
files=('2022/6/20/6.csv')
file_format=MATCH_DETAILS_FILEFORMAT, parameters: None
[2022-06-20 06:47:40,157] {cursor.py:710} INFO - query: [COPY INTO STAGING_MATCHDETAILS FROM @MY_AZURE_MATCH_DETAILS_STAGE/ files=('2022/...]
[2022-06-20 06:47:41,439] {cursor.py:734} INFO - query execution done
[2022-06-20 06:47:41,440] {snowflake.py:334} INFO - Statement execution info - {'file': 'azure://leagueoflegends.blob.core.windows.net/match-details/2022/6/20/6.csv', 'status': 'LOADED', 'rows_parsed': 20, 'rows_loaded': 20, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-06-20 06:47:41,440] {snowflake.py:338} INFO - Rows affected: 1
[2022-06-20 06:47:41,441] {snowflake.py:339} INFO - Snowflake query id: 01a51177-0000-fac2-0000-d96900054752
[2022-06-20 06:47:41,441] {connection.py:507} INFO - closed
[2022-06-20 06:47:41,474] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-06-20 06:47:41,536] {azureToSnowflake.py:75} INFO - COPY command completed
[2022-06-20 06:47:41,547] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=match_details_dag, task_id=paths.path_matchdetails.azure_matchdetails_snowflake, execution_date=20220618T000000, start_date=20220620T064739, end_date=20220620T064741
[2022-06-20 06:47:41,582] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-20 06:47:41,614] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 06:47:41,630] {dagrun.py:627} WARNING - Failed to get task '<TaskInstance: match_details_dag.chck scheduled__2022-06-18T00:00:00+00:00 [removed]>' for dag 'match_details_dag'. Marking it as removed.
[2022-06-20 06:47:41,636] {dagrun.py:566} ERROR - Deadlock; marking run <DagRun match_details_dag @ 2022-06-18 00:00:00+00:00: scheduled__2022-06-18T00:00:00+00:00, externally triggered: False> failed
[2022-06-20 06:47:41,636] {dagrun.py:590} INFO - DagRun Finished: dag_id=match_details_dag, execution_date=2022-06-18 00:00:00+00:00, run_id=scheduled__2022-06-18T00:00:00+00:00, run_start_date=None, run_end_date=2022-06-20 06:47:41.636578+00:00, run_duration=None, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-06-18 00:00:00+00:00, data_interval_end=2022-06-18 01:00:00+00:00, dag_hash=874004d3a7725a3c1a78d5f660cc10df
[2022-06-20 06:47:41,636] {dagrun.py:749} WARNING - Failed to record duration of <DagRun match_details_dag @ 2022-06-18 00:00:00+00:00: scheduled__2022-06-18T00:00:00+00:00, externally triggered: False>: start_date is not set.
