[2022-05-20 04:34:12,975] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_maps.azure_maps_snowflake manual__2022-05-20T04:34:01.422037+00:00 [queued]>
[2022-05-20 04:34:12,989] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: league_of_legends_dag.paths.path_maps.azure_maps_snowflake manual__2022-05-20T04:34:01.422037+00:00 [queued]>
[2022-05-20 04:34:12,989] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:34:12,990] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-05-20 04:34:12,990] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-05-20 04:34:13,002] {taskinstance.py:1264} INFO - Executing <Task(AzureDataLakeToSnowflakeTransferOperator): paths.path_maps.azure_maps_snowflake> on 2022-05-20 04:34:01.422037+00:00
[2022-05-20 04:34:13,009] {standard_task_runner.py:52} INFO - Started process 4454 to run task
[2022-05-20 04:34:13,012] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'league_of_legends_dag', 'paths.path_maps.azure_maps_snowflake', 'manual__2022-05-20T04:34:01.422037+00:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/dataDragon_dag.py', '--cfg-path', '/tmp/tmpu1t8enpb', '--error-file', '/tmp/tmpau7dxr0v']
[2022-05-20 04:34:13,013] {standard_task_runner.py:77} INFO - Job 644: Subtask paths.path_maps.azure_maps_snowflake
[2022-05-20 04:34:13,076] {logging_mixin.py:109} INFO - Running <TaskInstance: league_of_legends_dag.paths.path_maps.azure_maps_snowflake manual__2022-05-20T04:34:01.422037+00:00 [running]> on host ca9a242fab95
[2022-05-20 04:34:13,132] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=league_of_legends_dag
AIRFLOW_CTX_TASK_ID=paths.path_maps.azure_maps_snowflake
AIRFLOW_CTX_EXECUTION_DATE=2022-05-20T04:34:01.422037+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-20T04:34:01.422037+00:00
[2022-05-20 04:34:13,133] {azureToSnowflake.py:73} INFO - Executing COPY command...
[2022-05-20 04:34:13,146] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.5.1, Python Version: 3.8.12, Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2022-05-20 04:34:13,146] {connection.py:868} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-05-20 04:34:13,147] {connection.py:886} INFO - Setting use_openssl_only mode to False
[2022-05-20 04:34:13,996] {cursor.py:637} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-05-20 04:34:14,125] {cursor.py:661} INFO - query execution done
[2022-05-20 04:34:14,126] {snowflake.py:324} INFO - Running statement: COPY INTO STAGING_DATADRAGON_MAPS
FROM @MY_AZURE_DATADRAGON_MAPS_STAGE/
files=('2022/5/20/4.json')
file_format=DATADRAGON_FILEFORMAT, parameters: None
[2022-05-20 04:34:14,127] {cursor.py:637} INFO - query: [COPY INTO STAGING_DATADRAGON_MAPS FROM @MY_AZURE_DATADRAGON_MAPS_STAGE/ files=('...]
[2022-05-20 04:34:14,738] {cursor.py:661} INFO - query execution done
[2022-05-20 04:34:14,738] {snowflake.py:334} INFO - Statement execution info - {'file': 'azure://leagueoflegends.blob.core.windows.net/datadragon-maps/2022/5/20/4.json', 'status': 'LOADED', 'rows_parsed': 1, 'rows_loaded': 1, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-05-20 04:34:14,739] {json_result.py:127} INFO - fetching data done
[2022-05-20 04:34:14,739] {snowflake.py:338} INFO - Rows affected: 1
[2022-05-20 04:34:14,741] {snowflake.py:339} INFO - Snowflake query id: 01a46292-0000-f1b3-0000-d96900037796
[2022-05-20 04:34:14,741] {connection.py:499} INFO - closed
[2022-05-20 04:34:14,798] {connection.py:502} INFO - No async queries seem to be running, deleting session
[2022-05-20 04:34:14,864] {azureToSnowflake.py:75} INFO - COPY command completed
[2022-05-20 04:34:14,883] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=league_of_legends_dag, task_id=paths.path_maps.azure_maps_snowflake, execution_date=20220520T043401, start_date=20220520T043412, end_date=20220520T043414
[2022-05-20 04:34:14,912] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-20 04:34:14,962] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
