[2022-06-20 22:57:45,414] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [queued]>
[2022-06-20 22:57:45,425] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [queued]>
[2022-06-20 22:57:45,425] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 22:57:45,425] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-06-20 22:57:45,425] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 22:57:45,436] {taskinstance.py:1264} INFO - Executing <Task(AzureDataLakeToSnowflakeTransferOperator): paths.path_matchinfo.azure_matchinfo_snowflake> on 2022-06-20 00:00:00+00:00
[2022-06-20 22:57:45,441] {standard_task_runner.py:52} INFO - Started process 86 to run task
[2022-06-20 22:57:45,443] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'paths.path_matchinfo.azure_matchinfo_snowflake', 'scheduled__2022-06-20T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmp1p7bab_g', '--error-file', '/tmp/tmpcgbm0c9s']
[2022-06-20 22:57:45,444] {standard_task_runner.py:77} INFO - Job 204: Subtask paths.path_matchinfo.azure_matchinfo_snowflake
[2022-06-20 22:57:45,494] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-20 22:57:45,541] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=paths.path_matchinfo.azure_matchinfo_snowflake
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-20T00:00:00+00:00
[2022-06-20 22:57:45,541] {azureToSnowflake.py:73} INFO - Executing COPY command...
[2022-06-20 22:57:45,550] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.12, Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2022-06-20 22:57:45,550] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-06-20 22:57:45,550] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-06-20 22:57:45,981] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-06-20 22:57:46,062] {cursor.py:734} INFO - query execution done
[2022-06-20 22:57:46,063] {snowflake.py:324} INFO - Running statement: COPY INTO STAGING_MATCHINFO
FROM @MY_AZURE_MATCH_INFO_STAGE/
files=('2022/6/20/22.csv')
file_format=MATCH_INFO_FILEFORMAT, parameters: None
[2022-06-20 22:57:46,063] {cursor.py:710} INFO - query: [COPY INTO STAGING_MATCHINFO FROM @MY_AZURE_MATCH_INFO_STAGE/ files=('2022/6/20/2...]
[2022-06-20 22:57:47,611] {cursor.py:734} INFO - query execution done
[2022-06-20 22:57:47,612] {snowflake.py:334} INFO - Statement execution info - {'file': 'azure://leagueoflegends.blob.core.windows.net/match-info/2022/6/20/22.csv', 'status': 'LOADED', 'rows_parsed': 100, 'rows_loaded': 100, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-06-20 22:57:47,612] {snowflake.py:338} INFO - Rows affected: 1
[2022-06-20 22:57:47,612] {snowflake.py:339} INFO - Snowflake query id: 01a51541-0000-fac3-0000-d969000558fe
[2022-06-20 22:57:47,612] {connection.py:507} INFO - closed
[2022-06-20 22:57:47,645] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-06-20 22:57:47,725] {azureToSnowflake.py:75} INFO - COPY command completed
[2022-06-20 22:57:47,735] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=match_details_dag, task_id=paths.path_matchinfo.azure_matchinfo_snowflake, execution_date=20220620T000000, start_date=20220620T225745, end_date=20220620T225747
[2022-06-20 22:57:47,786] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-20 22:57:47,817] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-20 23:21:37,789] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [queued]>
[2022-06-20 23:21:37,799] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [queued]>
[2022-06-20 23:21:37,800] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:21:37,800] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-06-20 23:21:37,800] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-20 23:21:37,813] {taskinstance.py:1264} INFO - Executing <Task(AzureDataLakeToSnowflakeTransferOperator): paths.path_matchinfo.azure_matchinfo_snowflake> on 2022-06-20 00:00:00+00:00
[2022-06-20 23:21:37,819] {standard_task_runner.py:52} INFO - Started process 362 to run task
[2022-06-20 23:21:37,821] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'match_details_dag', 'paths.path_matchinfo.azure_matchinfo_snowflake', 'scheduled__2022-06-20T00:00:00+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/matchData_dag.py', '--cfg-path', '/tmp/tmphkc88whm', '--error-file', '/tmp/tmp7_kwtjm6']
[2022-06-20 23:21:37,822] {standard_task_runner.py:77} INFO - Job 224: Subtask paths.path_matchinfo.azure_matchinfo_snowflake
[2022-06-20 23:21:37,868] {logging_mixin.py:109} INFO - Running <TaskInstance: match_details_dag.paths.path_matchinfo.azure_matchinfo_snowflake scheduled__2022-06-20T00:00:00+00:00 [running]> on host ebe3cc7dbee2
[2022-06-20 23:21:37,917] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=match_details_dag
AIRFLOW_CTX_TASK_ID=paths.path_matchinfo.azure_matchinfo_snowflake
AIRFLOW_CTX_EXECUTION_DATE=2022-06-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-20T00:00:00+00:00
[2022-06-20 23:21:37,918] {azureToSnowflake.py:73} INFO - Executing COPY command...
[2022-06-20 23:21:37,928] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.12, Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2022-06-20 23:21:37,929] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-06-20 23:21:37,929] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-06-20 23:21:38,515] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-06-20 23:21:38,683] {cursor.py:734} INFO - query execution done
[2022-06-20 23:21:38,684] {snowflake.py:324} INFO - Running statement: COPY INTO STAGING_MATCHINFO
FROM @MY_AZURE_MATCH_INFO_STAGE/
files=('2022/6/20/23.csv')
file_format=MATCH_INFO_FILEFORMAT, parameters: None
[2022-06-20 23:21:38,684] {cursor.py:710} INFO - query: [COPY INTO STAGING_MATCHINFO FROM @MY_AZURE_MATCH_INFO_STAGE/ files=('2022/6/20/2...]
[2022-06-20 23:21:40,011] {cursor.py:734} INFO - query execution done
[2022-06-20 23:21:40,011] {snowflake.py:334} INFO - Statement execution info - {'file': 'azure://leagueoflegends.blob.core.windows.net/match-info/2022/6/20/23.csv', 'status': 'LOADED', 'rows_parsed': 100, 'rows_loaded': 100, 'error_limit': 1, 'errors_seen': 0, 'first_error': None, 'first_error_line': None, 'first_error_character': None, 'first_error_column_name': None}
[2022-06-20 23:21:40,012] {snowflake.py:338} INFO - Rows affected: 1
[2022-06-20 23:21:40,012] {snowflake.py:339} INFO - Snowflake query id: 01a51559-0000-fac2-0000-d96900054b0e
[2022-06-20 23:21:40,012] {connection.py:507} INFO - closed
[2022-06-20 23:21:40,047] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-06-20 23:21:40,112] {azureToSnowflake.py:75} INFO - COPY command completed
[2022-06-20 23:21:40,123] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=match_details_dag, task_id=paths.path_matchinfo.azure_matchinfo_snowflake, execution_date=20220620T000000, start_date=20220620T232137, end_date=20220620T232140
[2022-06-20 23:21:40,163] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-20 23:21:40,192] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
